replicaCount: 1

image:
  repository: ghcr.io/ozeliurs/winbindex-api
  tag: main
  pullPolicy: Always

service:
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: winbindex-api.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: true
  accessModes: [ReadWriteOnce]
  size: 60Gi
  storageClass: ""
  existingClaim: ""

scraper:
  schedule: "17 3 * * 0"
  maxConcurrentRequests: "40"
  requestDelaySeconds: "0.1"
  minimumIntervalSeconds: "604800"

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
